Add Liquidation + Oracle + Hard Cash Out (WIP)
PaulFrambot/leech-contracts pull request #6
Opened 2021-07-08 11:29 UTC by MerlinEgalite

2021-07-08 20:07 UTC, MathisGD requested changes

2021-07-08 20:07 UTC, MathisGD commented on contracts/CompoundModule.sol
> +    function getAccountLiquidity(address _borrower) external view returns (uint256, uint256) {
what we need to do in this function :
calculate the "health factor" of the borrower (collateral / debt)
(it requires to covert collateral (ctoken) to token)

2021-07-08 20:07 UTC, MathisGD commented on contracts/CompoundModule.sol
> +        uint256 collateralNeededInCDai = collateralNeededInDai
302 -> 306 unusful now

2021-07-08 20:07 UTC, MathisGD commented on contracts/CompoundModule.sol
> +            uint256 daiAmountToTransfer = collateralBalanceOf[_borrower].unused
to update : 
what we transfert is collateral balance -> convert from ctoken to token -> minus debt

2021-07-08 21:15 UTC, MathisGD commented on contracts/CompoundModule.sol
> +            uint256 daiAmountToTransfer = collateralBalanceOf[_borrower].unused
We transfert collateral * amount / debt

2021-07-08 21:32 UTC, MerlinEgalite commented on contracts/CompoundModule.sol
> +        uint256 collateralNeededInCDai = collateralNeededInDai
done

2021-07-08 21:34 UTC, MerlinEgalite commented on contracts/CompoundModule.sol
> +            uint256 daiAmountToTransfer = collateralBalanceOf[_borrower].unused
I need to study more in depth compound mechanism here https://github.com/compound-finance/compound-protocol/blob/b9b14038612d846b83f8a009a82c38974ff2dcfe/contracts/Comptroller.sol#L773-L800

2021-07-08 22:13 UTC, MathisGD commented on contracts/CompoundModule.sol
> +    function getAccountHealthFactor(address _borrower) public returns (uint256) {
ok for me

2021-07-08 22:26 UTC, MathisGD requested changes

2021-07-08 22:26 UTC, MathisGD commented on contracts/CompoundModule.sol
>      function _redeemCollateral(address _borrower, uint256 _amount) internal {
we should check that the collateral balance after this trade is enough for supporting the current borrowing position (otherwise you are no longer collateralised and leave your debt unpaid forever) 

it should look like this : 
require( collateralNeeded < collateralAfterRedeem )

2021-07-08 22:26 UTC, MathisGD commented on contracts/CompoundModule.sol
>      function _redeemCollateral(address _borrower, uint256 _amount) internal {
otherwise, collateralBalanceOf update seems good to me

2021-07-08 22:26 UTC, MathisGD commented on contracts/CompoundModule.sol
>      function borrow(uint256 _amount) external {
ok for me

2021-07-08 22:26 UTC, MathisGD commented on contracts/CompoundModule.sol
> +        uint256 daiAmountToTransfer = repayAmountInDai
ok for me, but we should verify on Compound

2021-07-09 10:45 UTC, MerlinEgalite commented on contracts/CompoundModule.sol
>      function _redeemCollateral(address _borrower, uint256 _amount) internal {
For now `redeemCollateral` can be triggered only if the borrower has no borrowingBalance so I think this is ok.

2021-07-09 10:48 UTC, MerlinEgalite commented on contracts/CompoundModule.sol
>      function _redeemCollateral(address _borrower, uint256 _amount) internal {
We can remove this requirement to allow the borrower to retrieve part of his collateral if her health factor is still >= 1 after redeem.

2021-07-09 10:52 UTC, MathisGD commented on contracts/CompoundModule.sol
>      function _redeemCollateral(address _borrower, uint256 _amount) internal {
Yes ok my bad
No need to add this in this PR but to keep in mind

2021-07-09 10:55 UTC, MerlinEgalite commented on contracts/CompoundModule.sol
>      function _redeemCollateral(address _borrower, uint256 _amount) internal {
Perfect I'll merge it and create a new one for those changes then.

2021-07-09 11:07 UTC, merged